apiVersion: apps/v1
kind: Deployment
metadata:
  name: safaripark-go-deployment
  labels:
    app: safaripark-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safaripark-go
  template:
    metadata:
      labels:
        app: safaripark-go
    spec:
      containers:
      - name: safaripark-go
        image: dockerhub.io/khaljimbo/safari-go:latest
        ports:
        - containerPort: 8000
