name: Docker Image CI

on:
  push:
    branches:
    - develop
    - release/*
    - feature/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t khaljimbo/safari-go:latest -f ../Dockerfile
    - name: Push the Docker image
      run: docker push khaljimbo/safari-go:latest
